### ISSUE TITLE
Feature Request: Custom MAC for UUID sandwich attack

### ISSUE THREAD

**Issue by Aituglo** [AethliosIK/reset-tolkien#11]
Hi ! 

Very nice tool, thank you so much for developing it, very helpful.

I'm writing this issue to give you a feature request for the next releases. It would be very nice if you could add the possibility of adding a custom MAC list for UUID sandwich attacks.

In fact, when looking for this type of vulnerability, there are multiple servers that can create the UUID, so managing the MAC Address for all of these servers and creating a list of possible UUID for each MAC can be nice!

Regards,
Aituglo

**Comment by AethliosIK** [comment]
Implemented in #14
